// <auto-generated />
using EFCoreTutorial2.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreTutorial2.Migrations
{
    [DbContext(typeof(MusicContext))]
    [Migration("20230718153247_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreTutorial2.Models.ArtistModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Johnny Cash"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jimmy Buffet"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home Free"
                        });
                });

            modelBuilder.Entity("EFCoreTutorial2.Models.GenreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rock and Roll"
                        },
                        new
                        {
                            Id = 2,
                            Name = "R&B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Country"
                        });
                });

            modelBuilder.Entity("EFCoreTutorial2.Models.SongModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("GenreId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            GenreId = 1,
                            Title = "You're Heartless"
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 1,
                            GenreId = 1,
                            Title = "Ride Bikes"
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 1,
                            GenreId = 2,
                            Title = "Wayfaring"
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 2,
                            GenreId = 3,
                            Title = "Son of a Sailor"
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 3,
                            GenreId = 3,
                            Title = "Sea Shanty"
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 2,
                            GenreId = 3,
                            Title = "Island"
                        });
                });

            modelBuilder.Entity("EFCoreTutorial2.Models.SongModel", b =>
                {
                    b.HasOne("EFCoreTutorial2.Models.ArtistModel", "Artist")
                        .WithMany("Songs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreTutorial2.Models.GenreModel", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("EFCoreTutorial2.Models.ArtistModel", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
